language: python
python:
  - "3.6"
install:
  - wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb
  - sudo dpkg -i pandoc-2.5-1-amd64.deb
  - pandoc -v
  - pip install -e .[test]
  - pip install black
  - pip install pylint
  - pip install coverage
  - pip install coveralls
script:
  - black --check pandoc_latex_tip.py setup.py tests/test_tip.py
  - pylint pandoc_latex_tip.py setup.py tests/test_tip.py
  - coverage run -a --source=pandoc_latex_tip setup.py test
after_success:
  - coveralls

